/**
 * This class is generated by jOOQ
 */
package example.dao.layer.rdbms.base.model.tables.records;


import example.dao.layer.rdbms.base.model.tables.Order;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderRecord extends UpdatableRecordImpl<OrderRecord> implements Record6<Integer, Integer, Long, String, Byte, Timestamp> {

    private static final long serialVersionUID = -1890205788;

    /**
     * Setter for <code>study.order.order_id</code>. 订单编号
     */
    public void setOrderId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>study.order.order_id</code>. 订单编号
     */
    public Integer getOrderId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>study.order.uid</code>. 用户Id
     */
    public void setUid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>study.order.uid</code>. 用户Id
     */
    public Integer getUid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>study.order.amout</code>. 订单金额(单位为分)
     */
    public void setAmout(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>study.order.amout</code>. 订单金额(单位为分)
     */
    public Long getAmout() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>study.order.remark</code>. ������ע
     */
    public void setRemark(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>study.order.remark</code>. ������ע
     */
    public String getRemark() {
        return (String) get(3);
    }

    /**
     * Setter for <code>study.order.status</code>. 订单状态
     */
    public void setStatus(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>study.order.status</code>. 订单状态
     */
    public Byte getStatus() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>study.order.order_time</code>. 订单时间
     */
    public void setOrderTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>study.order.order_time</code>. 订单时间
     */
    public Timestamp getOrderTime() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Long, String, Byte, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Long, String, Byte, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Order.ORDER.ORDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Order.ORDER.UID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Order.ORDER.AMOUT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Order.ORDER.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return Order.ORDER.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Order.ORDER.ORDER_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getAmout();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getOrderTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value1(Integer value) {
        setOrderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value2(Integer value) {
        setUid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value3(Long value) {
        setAmout(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value4(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value5(Byte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value6(Timestamp value) {
        setOrderTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord values(Integer value1, Integer value2, Long value3, String value4, Byte value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderRecord
     */
    public OrderRecord() {
        super(Order.ORDER);
    }

    /**
     * Create a detached, initialised OrderRecord
     */
    public OrderRecord(Integer orderId, Integer uid, Long amout, String remark, Byte status, Timestamp orderTime) {
        super(Order.ORDER);

        set(0, orderId);
        set(1, uid);
        set(2, amout);
        set(3, remark);
        set(4, status);
        set(5, orderTime);
    }
}
