/**
 * This class is generated by jOOQ
 */
package example.dao.layer.rdbms.base.model;


import example.dao.layer.rdbms.base.model.tables.Order;
import example.dao.layer.rdbms.base.model.tables.OrderLog;
import example.dao.layer.rdbms.base.model.tables.SchemaVersion;
import example.dao.layer.rdbms.base.model.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Study extends SchemaImpl {

    private static final long serialVersionUID = -1685242374;

    /**
     * The reference instance of <code>study</code>
     */
    public static final Study STUDY = new Study();

    /**
     * The table <code>study.order</code>.
     */
    public final Order ORDER = example.dao.layer.rdbms.base.model.tables.Order.ORDER;

    /**
     * 订单状态变化表
     */
    public final OrderLog ORDER_LOG = example.dao.layer.rdbms.base.model.tables.OrderLog.ORDER_LOG;

    /**
     * The table <code>study.schema_version</code>.
     */
    public final SchemaVersion SCHEMA_VERSION = example.dao.layer.rdbms.base.model.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * The table <code>study.user</code>.
     */
    public final User USER = example.dao.layer.rdbms.base.model.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Study() {
        super("study", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Order.ORDER,
            OrderLog.ORDER_LOG,
            SchemaVersion.SCHEMA_VERSION,
            User.USER);
    }
}
